### ISSUE TITLE
Test rw_pass_cell with loom

### ISSUE THREAD

**Issue by rphmeier** [thrumdev/nomt#167]
https://docs.rs/loom/latest/loom/ is a simulation toolkit providing ~drop-in replacements for atomics, `UnsafeCell` and other low-level synchronization primitives. Loom simulates all possible thread schedulings and ensures safety in testing.

**Comment by gabriele-0201** [comment]
After a brief look, I think there are many drop-in replacements, but not for two important primitives used in `rw_pass_cell`: `loom::sync::Arc` doesn't provide `downgrade`, requiring a conversion to `std::sync::Arc`, and `UnsafeCell` does not have `get` but uses `with` and `with_mut` to track cell access. This makes replicating the functionality of `ReadPass` and `WritePass` impossible, I think. Using `loom` with very high probability will introduce some overhead to handle differences between `std` and `loom` datatypes. I'll now attempt to see if these issues are or not as significant as they appear to me
