### ISSUE TITLE
benchtop: custom workload panics

### ISSUE THREAD

**Issue by gabriele-0201** [thrumdev/nomt#198]
After #184, benchtop panics if no `--workload-capacity` is provided because in `benchtop/src/custom_workload.rs`:

```rust
for _ in 0..n_reads {
    let key = rng.gen_range(0..self.db_size);
    // ...
```

If `self.db_size == 0`, then `gen_range` panics.

However, with this bug, another question arises: why are read and write keys randomly generated among the already present keys and not uniformly distributed across the entire key space as before?

If this behavior is the one required by benchtop, then an easy fix would be to make that flag mandatory

**Comment by rphmeier** [comment]
I fixed this.

> why are read and write keys randomly generated among the already present keys and not uniformly distributed across the entire key space as before

We should just add something like the percentage_cold flag we currently have for transfers, but for rw. Maybe just reuse that flag. But it we randomly distribute reads/writes across the entire keyspace (u64), we will basically never read existing keys. that doesn't seem desirable.

side node: percentage cold should be renamed to percentage fresh, in my opinion. "cold" to me means "not in cache", whereas "fresh" means "does not yet exist".

**Comment by rphmeier** [comment]
Moved to Linear
