### ISSUE TITLE
Design: sub-tree Depth management

### ISSUE THREAD

**Issue by gabriele-0201** [thrumdev/nomt#20]
Pages will store a rootless sub-binary tree of depth `d`. Should `d` be generic? Or should we stick with only one value hardcoded as a constant in the crate for the first phase? One problem with keeping it generic is that we need to use `#![feature(generic_const_exprs)]`, and the only way I could make it work is this:

```rust
pub struct Depth<const N: usize>;

pub struct Page<const D: usize>
where
    Depth<{ (1 << (D + 1)) - 2 }>: Sized,
{
    nodes: [Node; (1 << (D + 1)) - 2],
}
```
because otherwise something simpler like the following would not compile
```rust
pub struct Page<const D: usize>{
    nodes: [Node; (1 << (D + 1)) - 2],
}
```
and this is the reason https://github.com/rust-lang/rust/issues/82509#issuecomment-1165533546

A tradeoff we could make is, instead of accepting the depth of the sub-tree, accepting the number of nodes. This would involve asking the user to perform the previous operation and check its correctness upon creation. It would look like:

```rust
pub struct Page<const N: usize>{
    nodes: [Node; N],
}
```

The same problem will apply to everything that needs the depth of the sub-tree to work, for example extracting PageIds from the KeyPath

**Comment by rphmeier** [comment]
Let's separate the two concerns:
  1. Should we support multiple page sizes?
  2. Should we implement this with a generic or with another approach to code generation?

Re (1): It seems quite likely that there are gains to be had by supporting multiple page sizes, as the ideal page size for any device is the SSD's internal page size. Depending on the degree of parallelism supported by a given SSD, being off by one or two orders of magnitude may not matter much: if you under-estimate the real page size, you do 2x as many reads, if you over-estimate you read 2x as much. Would need benchmarking on a variety of different devices to say for sure. **Without a driving performance need, I am in favor picking a single page size for milestones 1 and 2 and revisiting in milestone 3**.

Re (2): Supporting multiple kinds of pages adds some implementation complexity. Most algorithms should be generic and reusable, but there are two challenges, the first of which you've raised: code generation. The second is page size detection.

**Comment by rphmeier** [comment]
> One problem with keeping it generic is that we need to use #![feature(generic_const_exprs)]

IMO using anything from nightly is a non-starter. We need to support stable Rust for this to be useful.

**Comment by pepyakin** [comment]
I agree with your logic on the №1, however, I don't think the genericity has any relevance.

What would we gain from using the const generics? I don't think much. All of that could be done with a variable specifying the actual size or the depth.

It would be nice to directly map `Page` to a memory page, but also having it defined as

```
// non repr(c)
struct Page {
  ptr: *mut Node,
  n: usize
}
```

works just as great.

**Comment by gabriele-0201** [comment]
> I am in favor picking a single page size for milestones 1 and 2 and revisiting in milestone 3

Great! I'm totally okay with this. It makes our lives much simpler and we would achieve the same goal for step 1 and 2!

> It would be nice to directly map Page to a memory page

I very like this idea!! This would achieve the same result as using const generic but without all the current disadvanges of using a nightly feature (and it seems to be even more fun to develop)

**Comment by rphmeier** [comment]
Marking this as solved - we will hold off on multiple page sizes and have agreed not to use generics to implement them at that point.
