### ISSUE TITLE
Question about encoding of leaves.

### ISSUE THREAD

**Issue by deuszx** [thrumdev/nomt#283]
[Docs state](https://github.com/thrumdev/nomt/blob/master/docs/nomt_specification.md#nodes) that leafs' address is given by hashing the key and hash of the value (`hash(key ++ hash(value))` while in code its address is represented by [hashing](https://github.com/thrumdev/nomt/blob/master/core/src/trie.rs#L121-L122) _path_ to the leaf and its value hash. Which is true then?

If it's the latter - does it mean the same value will have a different leaf depending on its location within the trie? different location == different path == different hash.

**Comment by rphmeier** [comment]
The leaf format is `key ++ hash(value)` and the hash of the leaf is `H(key ++ hash(value))`.

KeyPath is actually the full key, not just the path to the particular leaf which commits to the key-value pair, so it doesn't vary as the leaf moves around in the trie.
