### ISSUE TITLE
Benchmark Tooling

### ISSUE THREAD

**Issue by rphmeier** [thrumdev/nomt#3]
Our goal here is to make things fast. So we'll need good tooling & test suites.

**Comment by gabriele-0201** [comment]
While conducting some tests, I noticed that generating diverse tree structures can be quite complex. Therefore, we could develop a tool capable of randomly creating structures based on specific parameters. Running each benchmark on different structures each time could lead to unexpected results, so having something that serializes those structures for later use could be really useful. These structures could be utilized for testing updates, proof creation, and other tasks on various backends. Such a tool could potentially be implemented in a separate "benches" crate and may use traits to facilitate conversion between this tree representation and the required format for each backend

**Comment by rphmeier** [comment]
Can you elaborate on the complexity?

I haven't dug into this personally, so my view here may be lacking information, but I had the impression we only needed a few practical test cases:
  1. expected case: lots of keys, uniformly distributed across the whole domain space
  2. worst case: lots of keys, uniformly distributed across tight domain ranges

**Comment by gabriele-0201** [comment]
> Can you elaborate on the complexity?

I was saying that we need a tool capable of generating random keys required by the test cases you described and potentially something to save them to avoid re-generating everything from scratch, which could possibly lead to errors in benchmarking if the data is always changing. Nothing too fancy, it certainly cannot be done by hand, so a tool is needed

**Comment by rphmeier** [comment]
benchtop is pretty good!
