### ISSUE TITLE
Extension range protocol problem

### ISSUE THREAD

**Issue by gabriele-0201** [thrumdev/nomt#425]
Inside leaf_stage and branch_stage when a worker has finished iterating over all its changeset tries one more time to answer the left neighbor, if there is a pending request, it is expected to be properly answered. In fact, after that, there is an `assert!(pending_left_request.is_none());`. However, this seems to be a problem, and here's why:

We have worker A who has finished its range and is asking for a range extension. Worker B has only worked on the first leaf in its range, so it has only one leaf change available, which is sent to A. However, this could imply that A requires another range extension (from an underfull to a degenerate split). Let's say that the range assigned to worker B was larger than a single leaf, so it has nothing in `leaf/branch_changes`. Despite this, it has not consumed its range, so worker B has nothing to return, and `try_answer_left_neighbor` keeps the pending left request, which is later asserted to be None.

A possible solution would be to add something in the message to represent an early stop in the range, so the left worker could continue work on fresh leaves that were assigned to the right worker.

**Comment by rphmeier** [comment]
What we should absolutely avoid is the suggestion to have the left worker take over work from the right worker. That adds a ton of complexity. Because communication between workers is one-way, right-to-left, and workers can always proceed across nodes from left-to-right, it’s provable that the work can always conclude even if there are some degenerate cases where performance degrades to single-threaded.

**Comment by rphmeier** [comment]
One problem I see, and maybe this is what you’re describing, is:

Worker A sends a request to its right neighbor worker B.
Worker B can’t answer the request, but it finishes its entire range. It connects worker A and C. But the pending request isn’t passed to worker C.

So I think the solution here is just to have worker B send worker C the pending request to answer.

**Comment by gabriele-0201** [comment]
> intention was that a pending request will be answered either after the next node the worker processes or after the very end.

yes, with #422 this should be now addressed

> communication between workers is one-way, right-to-left

yes, I never intended to introduce the opposite direction

> Can you provide an example?

Let's try to explain a concrete example. Every column is a leaf, and each cell is a key-value pair in a leaf. 'k' stands for key and 'vs' for value_size.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<colgroup>
<col  class="org-left" />
<col  class="org-left" />
<col  class="org-left" />
<col  class="org-left" />
<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">leaf 1</th>
<th scope="col" class="org-left">leaf 2</th>
<th scope="col" class="org-left">leaf 3</th>
<th scope="col" class="org-left">leaf 4</th>
<th scope="col" class="org-left">leaf 5</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-left">k: 1 - vs:1100</td>
<td class="org-left">k: 4 - vs: 900</td>
<td class="org-left">k: 10 - vs:1200</td>
<td class="org-left">k: 15 - vs:1200</td>
<td class="org-left">k: 18 - vs:1100</td>
</tr>
</tbody>
<tbody>
<tr>
<td class="org-left">k: 2 - vs:1000</td>
<td class="org-left">k: 5 - vs: 900</td>
<td class="org-left">k: 11 - vs:1100</td>
<td class="org-left">k: 16 - vs:1100</td>
<td class="org-left">k: 19 - vs:1000</td>
</tr>
</tbody>
<tbody>
<tr>
<td class="org-left">k: 3 - vs:1000</td>
<td class="org-left">k: 7 - vs: 900</td>
<td class="org-left">k: 13 - vs:700</td>
<td class="org-left">k: 17 - vs:700</td>
<td class="org-left">k: 20 - vs:500</td>
</tr>
</tbody>
<tbody>
<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">k: 8 - vs: 900</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>


We have these leaves in our database and within a session, the following keys are going to be eliminated: `[7, 8, 13]`. The `commit_concurrency` is 2, and thus we have two workers, A and B, whose ranges respectively start and stop at key 10.

1. Worker A will remove 7 and 8 from leaf 2, then request a range extension to B.
2. Meanwhile, B has just deleted key 13 from leaf 3, creating a new LeafChanges item containing 10 and 11, which will be sent to worker A in `try_answer_left_neighbor`.
3. Now, A attempts to create a leaf with keys 4, 5, 10, and 11, which is an underfull to degenerate split. Thus, a left leaf with keys 4, 5, and 10 is created, however a pending 11 requires to be inserted into a new leaf along with the results of another range extension.
4. The issue arises as worker B fails to respond because it has no more items in the LeafChanges map and has not consumed its own range.

What B should do is send LeafChanges items along with information to utilize a portion of its range to fulfill the range extension.

Currently, this issue on the master branch does not cause any panic due to #420. However, it results in incorrect behavior. Testing it with #420 triggers a panic because the handle to the left worker is dropped prematurely.

> One problem I see ...

This problem is already being addressed by having `request_range_extension` recursively call the provided new right neighbor. Worker A would resend the request to C as soon as B answered.

**Comment by gabriele-0201** [comment]
One thing I just thought about: when I said "it results in incorrect behavior," that's because a leaf, which is *not* the last one, is created without having a size bigger than `LEAF_MERGE_THRESHOLD`.

Did you maybe think about letting leaves across boundaries not fulfill this constraint?

Because I'm pretty sure this is not required for the *last* leaf, as there would be no way to merge with the right sibling.

If the half-full requirement is not needed for those special leaves, then a simple solution is to close #420 and have some leaves occupied by less than half, but this can happen only at the bounds of the worker; thus, it should not have much impact

**Comment by rphmeier** [comment]
Thanks for the more detailed explanation.

> I would generalize the problem as follows: sometimes a worker finishes their job before reaching the end of the range, or they skip some nodes. We need to find a way to provide those unutilized nodes to the previous worker if they are needed. 

I agree with this framing.

It seems like the main oversight here is actually how we determine whether a range is 'consumed'. If a worker has finished all the work in its range, then we should say that the range is consumed and just stitch together the two workers, yielding all of the items in B's range to A. We would need to change the worker communication protocol to support this case, but that should be fairly simple.

Do you think this would fix the issue?

> One possibility is to accept underflow between range workers and possibly stop completely using the range extension, leaving each worker to perform their job without communication with each other.

The main downside of this approach is that it can lead to a lot of underfull leaves, for the reason that range bounds are determined dynamically based on the current workload. Let's try to avoid this.

**Comment by gabriele-0201** [comment]
I totally agree that a change in the communication protocol will fix the issue! I will publish a PR tomorrow with the fix if the review in #422 does not require too many changes to the code! (It will not leave any underfull leaf)
