### ISSUE TITLE
Reproducing benchmark numbers

### ISSUE THREAD

**Issue by danielwlz** [thrumdev/nomt#611]
Hi! I ran some benchmarks to try and reproduce your numbers, and would like to check that I am interpreting the numbers right. 

For instance, these are the best results I got after playing around with parameters. This is from running S=50000*26=130K ops and 4M accounts:

> ./benchtop/target/release/benchtop init -b nomt -c 22 -w transfer --buckets 4000000
> ./benchtop/target/release/benchtop run -w transfer -b nomt -s 1300000 -c 22 --time-limit 60s --workload-concurrency 256 --commit-concurrency 256

**Results:**

> 
> metrics
>   page requests         39227772
>   page cache misses     25497023 - 65.00% of page requests
>   value fetch mean      70447 ns
> nomt
>   mean workload: 16030 ms
>   mean read: 55935 ns
>   mean commit_and_prove: 15396 ms
>   mean throughput: 81094.8 ops/s

What I'm reading from here is: 
- 81k updates per second
- mean read latency of 56µs
- 41k TPS*

Does this sound right? 

*if I take an txn as 2 read-writes, I divide 81094.8/2 = 41k TPS which is close to the 40k TPS mentioned in the Nov 2024 slides (albeit this is for 4M accounts and not 128M).

I'm running this on a AWS i3en.metal instance (96 vCPUs, 768GB RAM, 8x 7.5TB SSDs for 2M IOPS with RAID0).

I'm seeing read latency vary quite a bit when I run with different parameters, is that normal? e.g., from 25 to  50µs.

What are the latest best numbers from your own benchmarking? Thank you so much! What you've done here is pretty neat.

**Comment by rphmeier** [comment]
Thank you for this wonderful datapoint from benchtop! We have been very curious about the performance of RAID0. The set-up looks good and all accurate.

> I'm seeing read latency vary quite a bit when I run with different parameters, is that normal? e.g., from 25 to 50µs.

I think this might be due to the RAID0. Your 56us mean latency tracks with the expected 40us + a long tail. With RAID0 we don't know which drive a random read will go to, which leads to occasional bursts all focused on a single drive rather than being uniformly balanced all on one drive. But 25us is quite low.  

> *if I take an txn as 2 read-writes, I divide 81094.8/2 = 41k TPS which is close to the 40k TPS mentioned in the Nov 2024 slides (albeit this is for 4M accounts and not 128M).

Actually this is 81k TPS (each op in this workload is a 2-reads-2-writes transaction).

> -s 1300000 

Note that `-s` here is a very large size (1.3M) per iteration. I've anecdotally observed better throughput with larger workload sizes, but a typical blockchain setting might have smaller blocks (e.g. 25-500k ops per block, depending on blocktime).

> What are the latest best numbers from your own benchmarking?

We don't have anything on RAID0, and just some anecdotal evidence from our own dev machines. I typically run with these parameters:

`-b nomt -w transfer -s 10000 -c 26 --workload-concurrency 64 --commit-concurrency 8`. this reliably achieves TPS measurements in the high 30k or low 40ks on my machines. When we prepare to release V1 we'll put up more numbers in a more rigorous environment.

> Thank you so much! What you've done here is pretty neat.

:heart:

**Comment by danielwlz** [comment]
I'm testing 4 billion accounts and am seeing pretty high SSD space usage of 15TB (or 3-4KB per account). I must be measuring it wrong, how do I measure SSD usage correctly? Thank you so much!

Other metrics seem reasonable (it's doing 20K+ TPS).

I reproduce the commands I ran below for transparency, along with the outputs of `time -v`. (Known issue: I meant to use -c 32 instead of 28.)

```
./benchtop/target/release/benchtop` init -b nomt -c 28 -w transfer --buckets 4000000000
        User time (seconds): 9352.01
        System time (seconds): 15272.24
        Percent of CPU this job got: 198%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 3:26:51
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 46238732
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1
        Minor (reclaiming a frame) page faults: 1055148598
        Voluntary context switches: 45208381
        Swaps: 0
        File system inputs: 3266934776
        File system outputs: 4877716496
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

```

```
> du -s *
82740	bbn
16008172392	ht
23267944	ln
4	meta
0	wal
```

```
./benchtop/target/release/benchtop run -b nomt -w transfer -s 10000 -c 28 --workload-concurrency 512 --commit-concurrency 512 --time-limit 120s

metrics
  page requests         40311124
  page cache misses     11459430 - 28.43% of page requests
  value fetch mean      205 us
nomt
  mean workload: 473 ms
  mean read: 206 us
  mean commit_and_prove: 426 ms
  mean throughput: 21138.7 ops/s

	User time (seconds): 2927.56
	System time (seconds): 384.33
	Percent of CPU this job got: 2163%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 2:33.05
	Maximum resident set size (kbytes): 8098884
	Major (requiring I/O) page faults: 11
	Minor (reclaiming a frame) page faults: 9596709
	Voluntary context switches: 8916524
	Involuntary context switches: 10231891
	File system inputs: 136842256
	File system outputs: 166016448
```

**Comment by rphmeier** [comment]
> `--buckets 4000000000`

This parameter doesn't determine the number of accounts (the `-c` flag does that) but rather the number of buckets to allocate for the hash table.

Each bucket is a 4KB page, so with 4 billlion buckets we'd expect 15TB of space just for the hash-table, whether it's used or not. The hash-table space is 100% preallocated, which means you're asking benchtop to reserve 15TB during initialization.

Choosing the number of buckets depends on the maximum size of the database; depending on the number of state items you need your database to store. 2^(last_multiple_of_6(log2(n_items))` plus a 25% margin. The way that we store merkle nodes grows the space in rough steps of 64x. So, for example, with 2^30 items you currently need about 1.25*2^30 buckets. That will hold up to 2^35. With some upcoming changes this'll shift by one, so for 2^30 items you'd only need 1.25*2^24 buckets. See [slide 30](https://hackmd.io/@Xo-wxO7bQkKidH1LrqACsw/rkG0lmjWyg#/30) of the presentation.

We also have strategies in theory for making this much more continuous with fewer space jumps, but they won't be part of V1.

(short version: try allocating 1.25 billion buckets instead, and this should be good up to 34 billion accounts)

> `-c 28` 

(as you mentioned) This indicates that you are creating a database with `2^28`=~268M accounts. For 4 billion accounts you'd rather have `-c 32`.

> how do I measure SSD usage correctly? Thank you so much!

We do have some code for determining the number of occupied buckets to get the actual occupancy, but it's not currently exposed through the CLI.

> `--commit-concurrency 512`

note that values over 64 currently are truncated to 64; I forgot to note this in my previous post

**Comment by danielwlz** [comment]
Ah, thanks so much for the the clarification! I will try again with the correct parameters.

**Comment by rphmeier** [comment]
Try adding more buckets; I'm not sure this safety margin is quite enough with some testing locally. But it's most of the way. You should be able to cut the number of buckets at least in half.

**Comment by rphmeier** [comment]
I made a python script that'll tell you exactly how many buckets you'll need: https://gist.github.com/rphmeier/0cb36fbedf61f38481d967e6a2f38cfb

For c=32 you need 1449235047.0 (5528.39 GB). With PR #619 that'd come down to ~4TB. With some future stuff it could come down a lot more. Add a 20% margin of error, but I've tested the projections up to 2^26 and it is very accurate.

**Comment by danielwlz** [comment]
Thank you for the script! I finished a run with 2^32 accounts and 1610612736 buckets. Thought you might be interested in the results (do they look reasonable to you and in line with your own benchmarks?)

In the interests of reproducibility, these are the commands I ran on a i3en.metal instance:

```
benchtop init -b nomt -c 32 -w transfer --buckets 1610612736
benchtop run -b nomt -w transfer -s 6250 -c 32 --workload-concurrency 64 --commit-concurrency 64 --time-limit 600s
benchtop run -b nomt -w transfer -s 125000 -c 32 --workload-concurrency 64 --commit-concurrency 64 --time-limit 600s
benchtop run -b nomt -w transfer -s 10000 -c 32 --workload-concurrency 64 --commit-concurrency 64 --time-limit 600s
```

These are key things I picked out:
- Population seems slow (71 hrs for 4B, or 16,762 accounts per second) in the current version
- 16K-18K transactions/second at 4 billion (2^32) accounts

Full outputs:
```
	Command being timed: "benchtop init -b nomt -c 32 -w transfer --buckets 1610612736"
	User time (seconds): 223105.06
	System time (seconds): 286544.81
	Percent of CPU this job got: 198%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 71:10:26
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 58814220
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1
	Minor (reclaiming a frame) page faults: 23388362981
	Voluntary context switches: 962103421
	Involuntary context switches: 326265972
	Swaps: 0
	File system inputs: 91985676640
	File system outputs: 116190079448
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
metrics
  page requests         185279492
  page cache misses     59076667 - 31.89% of page requests
  value fetch mean      120 us
nomt
  mean workload: 386 ms
  mean read: 121 us
  mean commit_and_prove: 359 ms
  mean throughput: 16158.5 ops/s
	Command being timed: "benchtop run -b nomt -w transfer -s 6250 -c 32 --workload-concurrency 64 --commit-concurrency 64 --time-limit 600s"
	User time (seconds): 10949.75
	System time (seconds): 1480.89
	Percent of CPU this job got: 2021%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 10:14.84
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 5381424
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 164
	Minor (reclaiming a frame) page faults: 9966284
	Voluntary context switches: 26505356
	Involuntary context switches: 3501976
	Swaps: 0
	File system inputs: 628409080
	File system outputs: 864137016
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
metrics
  page requests         199522326
  page cache misses     110651627 - 55.46% of page requests
  value fetch mean      127 us
nomt
  mean workload: 6746 ms
  mean read: 128 us
  mean commit_and_prove: 6196 ms
  mean throughput: 18528.3 ops/s
	Command being timed: "benchtop run -b nomt -w transfer -s 125000 -c 32 --workload-concurrency 64 --commit-concurrency 64 --time-limit 600s"
	User time (seconds): 2569.58
	System time (seconds): 3536.03
	Percent of CPU this job got: 991%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 10:15.87
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 17232040
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 162
	Minor (reclaiming a frame) page faults: 33355540
	Voluntary context switches: 75634886
	Involuntary context switches: 2873948
	Swaps: 0
	File system inputs: 670255368
	File system outputs: 795503336
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
metrics
  page requests         187527992
  page cache misses     70209305 - 37.44% of page requests
  value fetch mean      121 us
nomt
  mean workload: 606 ms
  mean read: 121 us
  mean commit_and_prove: 563 ms
  mean throughput: 16492.6 ops/s
	Command being timed: "benchtop run -b nomt -w transfer -s 10000 -c 32 --workload-concurrency 64 --commit-concurrency 64 --time-limit 600s"
	User time (seconds): 11660.65
	System time (seconds): 1519.74
	Percent of CPU this job got: 2142%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 10:15.10
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 5957392
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 164
	Minor (reclaiming a frame) page faults: 9161485
	Voluntary context switches: 29989266
	Involuntary context switches: 3450274
	Swaps: 0
	File system inputs: 642354128
	File system outputs: 861902544
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0


```

**Comment by rphmeier** [comment]
At 2^26 I get around 86k accounts per second. 2^27 gives 48k accounts per second. So there is a clear drop-off.

**Comment by danielwlz** [comment]
Thank you for the quick and helpful feedback! Totally understand that init isn’t a priority for optimizing right now. Thanks for verifying the drop off.

I’m using RAID0 as it seemed to be the only way to get >1M IOPS capacity on AWS; I don’t currently have access to a single drive SSD with >1M IOPS, like the ones mentioned in the Nov2024 Sub0 talk.

Other folks pointed me to NOMT, saying it was a very promising entrant in the space (storage + merklelization). Will certainly be keen to get in touch and discuss further! Working on a deadline now, but will drop you an email within a week / as soon as I can. Thank you again!

**Comment by danielwlz** [comment]
@rphmeier So sorry for the late followup - things got in the way timeline-wise, but I'm keen to share what I've been working on! I just sent you an email - let me know if you didn't get it. Looking forward to hearing your thoughts!
