### ISSUE TITLE
Design: Determine Leaf Node Encodings

### ISSUE THREAD

**Issue by rphmeier** [thrumdev/nomt#8]
Let's discuss the main approach of encoding leaves with partial keys embedded as well as possible alternatives where partial key information is stored to the side.

**Comment by rphmeier** [comment]
Having reflected on it, I think the best leaf format is this:

```rust
struct Leaf {
  // full path to key
  key_path: [u8; 32],
  // hash of value.
  value_hash: [u8; 32],
}
```

We have two key goals in the leaf node:
  1. Ensure positional independence: moving a leaf's location in the trie should not require altering its data
  2. Encapsulate key information: the merkle root hash alone should be the only root of trust required to prove anything in the trie.

A leaf structure which contains the value hash but no key information achieves goal (1) but not (2). A leaf structure containing only the "partial key" (remaining key path) achieves (2) but not (1). The leaf structure above achieves both.

**Comment by rphmeier** [comment]
We should also address the semantic difference of "no value" and "has value, empty". For this, I suggest we use the zero hash. This gives us the following semantics:
  1. Zero hash: no value.
  2. `hash([]): has value, empty.
  3. `hash(x != []): has value x.

only case (1) should be elided with #12

**Comment by gabriele-0201** [comment]
Updates introduced in #16 define `LeafData` that contains what compose a Leaf. It is formed in the same way as what you previously defined in the `struct Leaf`. The effective internal encoding of a `LeafData` (what will be stored in the tree) is the hash of the concatenation of `key_path` and `value_hash`.

The semantic difference between "no value" and "has value, empty" remains unchanged for 1, while 2 and 3 seem to be combined, with the hash of the value being concatenated with the key. Therefore, there will always be something to effectively hash, even with an empty value

**Comment by rphmeier** [comment]
Adding some specificity to my last post using the leaf data structure from #16 :

```rust
let no_value = LeafData { key, value_hash: ZERO };
let empty_value = LeafData { key, value_hash: h([]) };
let nonempty_value = LeafData { key, value_hash: h(x != []) };

let no_value_leaf = TERMINATOR;
let empty_leaf = h(LeafData { key, value_hash: h([]) });
let nonempty_value = h(LeafData { key, value_hash: h(x != []) }
```
